version: "3"

services:
  # go services
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - store
    ports:
      - "8081:8080"
    environment:
      PQ_HOST:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      PQ_NAME:       "postgres"
      STARTUP_SLEEP: "5"
      STORE_PROXY: "http"
      STORE_HOST:  "store"
      STORE_PORT:  "8080"
  dispatch:
    build:
      context: .
      dockerfile: ./dispatch/Dockerfile
    depends_on:
      - postgres
      - flush
    environment:
      DISPATCH_RATE: "2"
      FLUSH_HOST:    "flush"
      FLUSH_PORT:    "8080"
      PQ_HOST:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      PQ_NAME:       "postgres"
      STARTUP_SLEEP: "5"
  ethereum:
    build: ./ethereum
    ports:
      - "8084:8080"
    environment:
      CONN:    "${ETHEREUM_HOST}"
      PRIVKEY: "${PRIVATE_KEY}"
  flush:
    build: ./flush
    depends_on:
      - ethereum
      - ipfs
      - postgres
    ports:
      - "8083:8080"
    environment:
      STARTUP_SLEEP: "5"
      ETH_HOST:      "ethereum"
      ETH_PORT:      "8080"
      ETH_ADDRESS:   "0x74e596525C63393f42C76987b6A66F4e52733efa"
      IPFS_HOST:     "ipfs"
      IPFS_PORT:     "5001"
      PQ_HOST:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      PQ_NAME:       "postgres"
  migrate:
    build: ./migrate
    environment:
      PQ_HOST:    "postgres"
      PQ_PORT:    "5432"
      PQ_USER:    "postgres"
      PQ_NAME:    "postgres"
  store:
    build: ./store
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8082:8080"
    environment:
      STARTUP_SLEEP: "5"
      IPFS_HOST:     "ipfs"
      IPFS_PORT:     "5001"
      PQ_HOST:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      PQ_NAME:       "postgres"
      TOPAZ_USER:    "966d1035-73a1-4e57-9D1f-95920524689a"
  # supporting services
  ipfs:
    build: ./ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
    volumes:
      - "./ipfs/staging:/export"
      - "./ipfs/data:/data/ipfs"
  postgres:
    build: ./postgres
    depends_on:
      - migrate
    ports:
      - "5432:5432"
