version: "3"

services:
  ## the database service provides the topaz database
  database:
    build:
      context: ./
      dockerfile: Dockerfile-database
    ports:
      - "${DB_PORT}:5432"
  ## the ethereum service for pushing txs to the networks
  ethereum:
    image: trufflesuite/ganache-cli
    command: -m ${GANACHE_MNEMONIC}
    ports:
      - "${GETH_PORT}:8545"
  ## the redis store provides to track blacklisted or expired JWTs
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - 'redis:/data'

volumes:
  redis:
