version: "3"

services:
  flush:
    build:
      context: .
      dockerfile: Dockerfile.flush
    ports:
      - "8081:8081"
  ipfs:
    image: "jbenet/go-ipfs:latest"
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
    volumes:
      - "./ipfs/staging:/export"
      - "./ipfs/data:/data/ipfs"
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
  store:
    build:
      context: .
      dockerfile: Dockerfile.store
    ports:
      - "8080:8080"
