FROM golang:1.12.4-alpine3.9 as builder

RUN apk add --update --no-cache libc6-compat \
        git \
        ca-certificates \
        build-base

RUN mkdir /topaz 
COPY . /topaz/

WORKDIR /topaz/api
RUN go build -mod=vendor -ldflags "-linkmode external -extldflags -static" -tags netgo -installsuffix netgo -a -o ../topaz-api .

WORKDIR /topaz

FROM alpine:3.9.3
COPY --from=builder /topaz/topaz-api .
CMD ["./topaz-api"]  
