version: "3"

services:
  ## the ipfs service provides dedication access to ipfs
  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    ports:
      - "${IPFS_PORT}:5001"
      - "4001:4001"
    volumes:
      - "./data:/data/ipfs"
      - "./staging:/export"
  ## the postgres service contains the topaz database
  postgres:
    build: ./postgres
    ports:
      - "${PQ_PORT}:5432"
  ## a redis store used to track blacklisted or expired JWTs
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - 'redis:/data'
volumes:
  redis:
