FROM golang:1.11

RUN mkdir /topaz 
ADD . /topaz/

RUN go get -u github.com/gobuffalo/packr/packr

WORKDIR /topaz/api
RUN go build -o ../topaz-api .

WORKDIR /topaz/batch
RUN go build -o ../topaz-batch .

WORKDIR /topaz/migrations
RUN packr build -o ../topaz-migrate .

WORKDIR /topaz