version: "3"

services:
  # Core Services

  ## the api service allows http access to topaz
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - store
    ports:
      - "8080:8080"
    environment:
      PQ_HOST:       "postgres"
      PQ_NAME:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      STARTUP_SLEEP: "5"
      STORE_HOST:    "store"
      STORE_PORT:    "8083"
      STORE_PROXY:   "http"

  ## the dispatch service triggers flush workers
  dispatch:
    build:
      context: .
      dockerfile: ./dispatch/Dockerfile
    depends_on:
      - flush
      - postgres
    environment:
      DISPATCH_RATE: "5"
      FLUSH_HOST:    "flush"
      FLUSH_PORT:    "8082"
      PQ_HOST:       "postgres"
      PQ_NAME:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      STARTUP_SLEEP: "5"

  ## the ethereum service communicates between Topaz and ethereum
  ethereum:
    build: ./ethereum
    ports:
      - "8081:8080"
    environment:
      CONN:    "${ETHEREUM_HOST}"
      PRIVKEY: "${PRIVATE_KEY}"

  ## the flush service flushes all pending objects for a user into IPFS
  flush:
    build:
      context: .
      dockerfile: ./flush/Dockerfile
    depends_on:
      - ethereum
      - ipfs
      - postgres
    ports:
      - "8082:8080"
    environment:
      ETH_ADDRESS:   "0x74e596525C63393f42C76987b6A66F4e52733efa"
      ETH_HOST:      "ethereum"
      ETH_PORT:      "8080"
      IPFS_HOST:     "ipfs"
      IPFS_PORT:     "5001"
      PQ_HOST:       "postgres"
      PQ_NAME:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      STARTUP_SLEEP: "5"

  ## the migrate service manages database migrations
  migrate:
    build: ./migrate
    environment:
      PQ_HOST:    "postgres"
      PQ_PORT:    "5432"
      PQ_USER:    "postgres"
      PQ_NAME:    "postgres"

  ## the store service manages the uploading of data to topaz
  store:
    build:
      context: .
      dockerfile: ./store/Dockerfile
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8083:8080"
    environment:
      IPFS_HOST:     "ipfs"
      IPFS_PORT:     "5001"
      PQ_HOST:       "postgres"
      PQ_NAME:       "postgres"
      PQ_PORT:       "5432"
      PQ_USER:       "postgres"
      STARTUP_SLEEP: "5"
      TOPAZ_USER:    "1"

  # Supporting Services

  ## the ipfs service provides dedication access to ipfs
  ipfs:
    build: ./ipfs
    ports:
      - "127.0.0.1:5001:5001"
      - "4001:4001"
    volumes:
      - "./ipfs/data:/data/ipfs"
      - "./ipfs/staging:/export"

  ## the postgres service contains the Topaz database
  postgres:
    build: ./postgres
    depends_on:
      - migrate
    ports:
      - "5432:5432"
