FROM golang:1.11-alpine

RUN apk add git gcc musl-dev

RUN mkdir /topaz 
ADD . /topaz/

WORKDIR /topaz/api
RUN go build -o ../topaz-api .

WORKDIR /topaz/batch
RUN go build -o ../topaz-batch .

WORKDIR /topaz/migrations
RUN go build -o ../topaz-migrate .

WORKDIR /topaz