version: "3"

services:
  dispatch:
    build: ./dispatch
    depends_on:
      - postgres
      - flush
    environment:
      FLUSH_HOST:  "flush"
      FLUSH_PORT:  "8080"
      PQ_HOST:     "postgres"
      PQ_PORT:     "5432"
      PQ_USER:     "postgres"
      PQ_NAME:     "postgres"
  flush:
    build: ./flush
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8080:8080"
    environment:
      ETH_HOST:   "host.docker.internal"
      ETH_PORT:   "8088"
      IPFS_HOST:  "ipfs"
      IPFS_PORT:  "5001"
      PQ_HOST:    "postgres"
      PQ_PORT:    "5432"
      PQ_USER:    "postgres"
      PQ_NAME:    "postgres"
  store:
    build: ./store
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8081:8080"
    environment:
      IPFS_HOST:  "ipfs"
      IPFS_PORT:  "5001"
      PQ_HOST:    "postgres"
      PQ_PORT:    "5432"
      PQ_USER:    "postgres"
      PQ_NAME:    "postgres"
      TOPAZ_USER: "966d1035-73a1-4e57-9D1f-95920524689a"
  ipfs:
    build: ./ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
    volumes:
      - "./ipfs/staging:/export"
      - "./ipfs/data:/data/ipfs"
  ethereum:
    build: ./ethereum
    environment:
      CONN:    "https://ropsten.infura.io"
      PRIVKEY: ""
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
